export const productArray = [
  {
    name: "Helly Hansen 1",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "1",
    price: 199,
    type: "man",
  },
  {
    name: "Helly Hansen 2",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "2",
    price: 199,
    type: "man",
  },
  {
    name: "Helly Hansen 3",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "3",
    price: 199,
    type: "man",
  },
  {
    name: "Helly Hansen 4",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "4",
    price: 199,
    type: "man",
  },
  {
    name: "Helly Hansen 5",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "5",
    price: 199,
    type: "man",
  },
  {
    name: "Helly Hansen 6",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "6",
    price: 199,
    type: "man",
  },
  {
    name: "Stormberg 1",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for women. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "7",
    price: 199,
    type: "woman",
  },
  {
    name: "Stormberg 2",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for women. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "8",
    price: 199,
    type: "woman",
  },
  {
    name: "Stormberg 3",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for women. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "9",
    price: 199,
    type: "woman",
  },
  {
    name: "Stormberg 4",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for woman. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "10",
    price: 199,
    type: "woman",
  },
  {
    name: "Stormberg 5",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for woman. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "11",
    price: 199,
    type: "woman",
  },
  {
    name: "Stormberg 6",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for woman. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "12",
    price: 199,
    type: "woman",
  },

];