export const productArray = [
  {
    name: "Helly Hansen",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "1",
    price: 199,
    type: "man",
  },
  {
    name: "Nike",
    description: "Sportswear windrunner",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "2",
    price: 299,
    type: "man",
  },
  {
    name: "Bergans",
    description: "Rainjacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "3",
    price: 149,
    type: "man",
  },
  {
    name: "Norrøna",
    description: "Sailor jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "4",
    price: 399,
    type: "man",
  },
  {
    name: "Seeland",
    description: "Hiking jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "5",
    price: 599,
    type: "man",
  },
  {
    name: "Volcom",
    description: "Urban rain jacket",
    detailDescription: "Waterproof and windproof rainjacket for men. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/men portrait.png",
    id: "6",
    price: 199,
    type: "man",
  },
  {
    name: "Volcom",
    description: "Urban rain jacket",
    detailDescription: "Waterproof and windproof rainjacket for women. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "7",
    price: 599,
    type: "woman",
  },
  {
    name: "Stormberg",
    description: "Hiking jacket",
    detailDescription: "Waterproof and windproof rainjacket for women. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "8",
    price: 499,
    type: "woman",
  },
  {
    name: "Helly Hansen",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for women. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "9",
    price: 399,
    type: "woman",
  },
  {
    name: "Seeland 4",
    description: "Sailor jacket",
    detailDescription: "Waterproof and windproof rainjacket for woman. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "10",
    price: 249,
    type: "woman",
  },
  {
    name: "Norrøna",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for woman. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "11",
    price: 299,
    type: "woman",
  },
  {
    name: "Bergans",
    description: "Windbreaker jacket",
    detailDescription: "Waterproof and windproof rainjacket for woman. Perfect for hiking and outdoor use. Comes in two colors.",
    image: "/images/pink-jacket-removebg-preview.png",
    id: "12",
    price: 199,
    type: "woman",
  },

];